language: r
cache: packages
latex: false
warnings_are_errors: false

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      before_install:
        - echo "deb http://repo.yandex.ru/clickhouse/deb/stable/ main/" | sudo tee -a /etc/apt/sources.list
        - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4
        - sudo apt-get update
        - sudo apt-get install clickhouse-client clickhouse-server
      before_script:
        - sudo sed -i '/<listen_host>::1/d' /etc/clickhouse-server/config.xml   # don't listen on localhost
        - sudo service clickhouse-server start    # not using builtin service directive, so that the steps are executed in the correct order

# faster builds by exploiting the number of cores
env:
  global:
    - MAKEFLAGS="-j 2"
