# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
fetch <- function(res, n) {
    .Call('RClickhouse_fetch', PACKAGE = 'RClickhouse', res, n)
}

#' @export
clearResult <- function(res) {
    invisible(.Call('RClickhouse_clearResult', PACKAGE = 'RClickhouse', res))
}

#' @export
hasCompleted <- function(res) {
    .Call('RClickhouse_hasCompleted', PACKAGE = 'RClickhouse', res)
}

#' @export
getRowCount <- function(res) {
    .Call('RClickhouse_getRowCount', PACKAGE = 'RClickhouse', res)
}

#' @export
getRowsAffected <- function(res) {
    .Call('RClickhouse_getRowsAffected', PACKAGE = 'RClickhouse', res)
}

#' @export
getStatement <- function(res) {
    .Call('RClickhouse_getStatement', PACKAGE = 'RClickhouse', res)
}

#' @export
resultTypes <- function(res) {
    .Call('RClickhouse_resultTypes', PACKAGE = 'RClickhouse', res)
}

#' @export
connect <- function(host, port, db, user, password, compression) {
    .Call('RClickhouse_connect', PACKAGE = 'RClickhouse', host, port, db, user, password, compression)
}

#' @export
disconnect <- function(conn) {
    invisible(.Call('RClickhouse_disconnect', PACKAGE = 'RClickhouse', conn))
}

#' @export
select <- function(conn, query) {
    .Call('RClickhouse_select', PACKAGE = 'RClickhouse', conn, query)
}

#' @export
insert <- function(conn, tableName, df) {
    invisible(.Call('RClickhouse_insert', PACKAGE = 'RClickhouse', conn, tableName, df))
}

#' @export
validPtr <- function(ptr) {
    .Call('RClickhouse_validPtr', PACKAGE = 'RClickhouse', ptr)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('RClickhouse_RcppExport_registerCCallable', PACKAGE = 'RClickhouse')
})
